### ISSUE TITLE
Code comment

### ISSUE THREAD

**Issue by RingOfStorms** [kryptonics/SadeikFinalProject#8]
While your code is generally pretty good, I did notice a lot of sort of copy pasted lines of code in methods that contains 6 if/elif blocks. Generally coding practice is that if you have any code copy pasted you're doing it wrong and you should be making a method. I see this in your six pile methods a lot.

I will create a PR on how I would change this code!

**Comment by RingOfStorms** [comment]
Made a PR for some changes that will address this. There are MANY more places you could cut down on copy pasted code by just using a for loop and changing your manual lists to an array like I did in the PR.

https://github.com/kryptonics/Sadeik_CSCI2270_FinalProject/pull/9

**Comment by kryptonics** [comment]
Ah ok. I had actually not thought of making extra functions to handle some of the repeating operations because I thought that attempting to generalize these operations into an outside function might cause the code to break more often than if each needed instance was just hard coded to ensure it would work for the parameters of each instance. Im quite glad to hear that there's a much more sane way to do it! ill take a look at the PR. Thank you so much!
